---
spec:
  template:
    spec:
      containers:
        - name: gcvp
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          resources:
            limits:
              memory: 1Gi
              cpu: 1000m
            requests:
              memory: 100Mi
              cpu: 250m